version: '3'

services:

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file: /home/rreis-de42/Documents/proto/.env
    networks:
      - soufixe
  
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    env_file: /home/rreis-de42/Documents/proto/.env
    networks:
      - soufixe
    
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    env_file: /home/rreis-de42/Documents/proto/.env
    networks:
      - soufixe

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/rreis-de42/data/mysql
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/rreis-de42/data/wordpress
      o: bind

networks:
  soufixe:
    name: soufixe
    driver: bridge